import { execSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export class IdeaToDeploy {
  async createProject(name: string, type: string = 'web'): Promise<string> {
    const dir = join(process.cwd(), name)
    mkdirSync(dir, { recursive: true })

    if (type === 'web') {
      writeFileSync(join(dir, 'index.html'), '<!DOCTYPE html><html><head><title>' + name + '</title></head><body><h1>' + name + '</h1></body></html>')
      writeFileSync(join(dir, 'style.css'), 'body { font-family: sans-serif; padding: 2rem; }')
      writeFileSync(join(dir, 'script.js'), 'console.log("Hello from ' + name + '")')
      writeFileSync(join(dir, 'README.md'), '# ' + name + '\n\nAuto-generated by ZYRAXON AI')
    }

    return dir
  }

  async deployToGitHubPages(projectDir: string): Promise<{ success: boolean; url?: string; error?: string }> {
    try {
      execSync('git init', { cwd: projectDir, stdio: 'pipe' })
      execSync('git add -A', { cwd: projectDir, stdio: 'pipe' })
      execSync('git commit -m "initial: auto-deployed by ZYRAXON AI"', { cwd: projectDir, stdio: 'pipe' })
      return { success: true }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  }
}
